### ISSUE TITLE
Relation lookups should use the orm schema relation name rather than the sql table names

### ISSUE THREAD

**Issue by forivall** [vidigami/backbone-sql#4]
With a schema like the following

foo.coffee:

```
class Foo extends Backbone.Model
  schema:
    bar: -> ['belongsTo', require('./bar')]
  url: 'postgres://root:root@127.0.0.1:5432/example/foos'
```

bar.coffee:

```
class Bar extends Backbone.Model
  schema:
    baz: 'Integer'
    buz: 'Integer'
  url: 'postgres://root:root@127.0.0.1:5432/example/bars'
```

Currently, queries look like this:

```
Foo.find {'bars.baz': 1, $sort: 'bars.buz'}, (err, foos) -> console.log foos
```

Ideally, they should look like this

```
Foo.find {'bar.baz': 1, $sort: 'bar.buz'}, (err, foos) -> console.log foos
```
